### ISSUE TITLE
TypeError: 'module' object is not callable (Python 3.11)

### ISSUE THREAD

**Issue by gjaskula99** [Operator873/Nagios-Discord#3]
## Current behaviour

Script returns an error while sending notification as follows. Execution is aborted and notification is not being sent.

Log entry:
```
[1733758284] wproc:   stderr line 01: Traceback (most recent call last):
[1733758284] wproc:   stderr line 02:   File "/usr/local/nagios/libexec/send-service.py", line 56, in <module>
[1733758284] wproc:   stderr line 03:     main(sys.argv)
[1733758284] wproc:   stderr line 04:   File "/usr/local/nagios/libexec/send-service.py", line 29, in main
[1733758284] wproc:   stderr line 05:     host = urllib.parse(data["host"])
[1733758284] wproc:   stderr line 06:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[1733758284] wproc:   stderr line 07: TypeError: 'module' object is not callable
```

### Environment
Raspberry Pi 5, Raspbian 12
Nagios Core Version 4.4.14 
Python 3.11.2

Behaviour on different Python versions is unknown.

## Possible solution
Script tries to call _urllib.parse_ as a function, but it’s actually a module, not a callable object.  However it can be called by specific functions from the module, such as _urllib.parse.quote_ or _urllib.parse.unquote_. For instance lines:

```
host = urllib.parse(data["host"])
serv = urllib.parse(data["servdesc"])
```
can be changed to:
```
host = urllib.parse.quote(data["host"])
serv = urllib.parse.quote(data["servdesc"])
```

This fixes the issue and makes notifications being sent as usual. This applies in the same manner to _send-host.py_.

**Comment by Operator873** [comment]
Thanks for bringing this to my attention. I'll work on it when time permits 😄

**Comment by Operator873** [comment]
Modified per your suggestion. I don't actively use Nagios anymore, so I am unable to test it. However, based on the doc I read for urllib and your input, I've made the changes which should correct the problem. Please give feedback if you see anything else wonky happening.
